name: Backend Tests & Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.7.1"

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-html pytest-json-report

    - name: Set up test environment
      run: |
        echo "DATABASE_URL=postgresql://test_user:test_password@localhost:5432/test_db" > .env.test
        echo "CLERK_WEBHOOK_SECRET=test_webhook_secret" >> .env.test
        echo "CLERK_ISSUER_URL=https://test.clerk.accounts.dev" >> .env.test
        echo "ADMIN_SECRET_KEY=test_admin_secret_key_for_ci" >> .env.test

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U test_user; do
          echo "Waiting for postgres..."
          sleep 2
        done

    - name: Run database migrations/setup
      run: |
        python -c "
        from app.database import engine
        from app import models
        models.Base.metadata.create_all(bind=engine)
        print('Database tables created successfully')
        "

    - name: Run tests with coverage
      run: |
        pytest \
          --cov=app \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          --html=reports/report.html \
          --self-contained-html \
          --json-report --json-report-file=reports/report.json \
          -v \
          tests/

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: backend
        name: codecov-backend

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: reports/

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff bandit safety

    - name: Run Ruff Check (Linting)
      run: ruff check app/ tests/

    - name: Run Ruff Format (Formatting Check)
      run: ruff format --check app/ tests/

    - name: Run Bandit (Security Linting)
      run: bandit -r app/ -f json -o bandit-report.json
      continue-on-error: true

    # - name: Run Safety (Dependency Security Check)
    #   run: safety scan --json --output safety-report.json
    #   continue-on-error: true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: "*-report.json"

  performance:
    runs-on: ubuntu-latest
    needs: test
    
    services:
      postgres:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust

    - name: Set up test environment
      run: |
        echo "DATABASE_URL=postgresql://test_user:test_password@localhost:5432/test_db" > .env
        echo "CLERK_WEBHOOK_SECRET=test_webhook_secret" >> .env
        echo "CLERK_ISSUER_URL=https://test.clerk.accounts.dev" >> .env
        echo "ADMIN_SECRET_KEY=test_admin_secret_key_for_ci" >> .env

    - name: Setup database
      run: |
        python -c "
        from app.database import engine
        from app import models
        models.Base.metadata.create_all(bind=engine)
        "

    - name: Run performance tests
      run: |
        # Start the server in background
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
        
        # Run load tests
        locust -f tests/performance/locustfile.py --host=http://localhost:8000 --users 50 --spawn-rate 5 --run-time 60s --html performance_report.html

    - name: Upload performance report
      uses: actions/upload-artifact@v4
      with:
        name: performance-report
        path: performance_report.html
